name: eesinference
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - arrow-cpp=3.0.0
  - blas=1.0
  - boost-cpp=1.73.0
  - brotli=1.0.9
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cudatoolkit=10.1.243
  - double-conversion=3.1.5
  - et_xmlfile=1.0.1
  - fastparquet=0.5.0
  - freetype=2.10.4
  - gflags=2.2.2
  - glog=0.4.0
  - grpc-cpp=1.26.0
  - icu=58.2
  - ignite=0.4.4
  - intel-openmp=2020.2
  - jdcal=1.4.1
  - joblib=1.0.1
  - jpeg=9b
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libboost=1.73.0
  - libcblas=3.8.0
  - libedit=3.1.20191231
  - libevent=2.1.8
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libllvm10=10.0.1
  - libpng=1.6.37
  - libprotobuf=3.11.2
  - libstdcxx-ng=9.1.0
  - libthrift=0.13.0
  - libtiff=4.1.0
  - libuv=1.40.0
  - llvmlite=0.35.0
  - lz4-c=1.9.3
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - ninja=1.10.2
  - numba=0.52.0
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openpyxl=3.0.7
  - openssl=1.1.1k
  - orc=1.6.5
  - packaging=20.9
  - pandas=1.2.3
  - pillow=8.1.2
  - pip=21.0.1
  - pyarrow=3.0.0
  - pyparsing=2.4.7
  - python=3.7.10
  - python-dateutil=2.8.1
  - python-snappy=0.6.0
  - python_abi=3.7
  - pytorch=1.7.1
  - pytz=2021.1
  - re2=2020.11.01
  - readline=8.1
  - scikit-learn=0.23.2
  - scipy=1.6.1
  - setuptools=52.0.0
  - six=1.15.0
  - snappy=1.1.8
  - sqlite=3.33.0
  - tbb=2020.3
  - threadpoolctl=2.1.0
  - thrift=0.11.0
  - tk=8.6.10
  - torchaudio=0.7.2
  - torchvision=0.8.2
  - typing_extensions=3.7.4.3
  - uriparser=0.9.3
  - utf8proc=2.6.1
  - wheel=0.36.2
  - xlrd=2.0.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - absl-py==0.12.0
    - antlr4-python3-runtime==4.8
    - cachetools==4.2.2
    - chardet==4.0.0
    - cycler==0.10.0
    - google-auth==1.30.1
    - google-auth-oauthlib==0.4.4
    - grpcio==1.38.0
    - hydra-core==1.0.3
    - hydra-joblib-launcher==1.1.1
    - idna==2.10
    - importlib-metadata==4.4.0
    - importlib-resources==5.1.4
    - kiwisolver==1.3.1
    - markdown==3.3.4
    - matplotlib==3.3.4
    - nflows==0.12
    - numexpr==2.7.3
    - oauthlib==3.1.1
    - omegaconf==2.0.6
    - opt-einsum==3.3.0
    - protobuf==3.17.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyknos==0.12.0
    - pyro-api==0.1.2
    - pyro-ppl==1.3.1
    - pyyaml==5.4.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - sbi==0.12.2
    - tables==3.6.1
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tqdm==4.61.0
    - urllib3==1.26.5
    - werkzeug==2.0.1
    - zipp==3.4.1
