# @package _group_
name: mlp
_target_: model.Stim2EMG
params:
  embedding:
    _target_: layers.feedforward.MLP
    in_size: 15
    hidden_sizes: 8
    dropout: 0
    activation: relu
  core:
    _target_: layers.feedforward.MultiColumnMLP
    in_size: 8
    hidden_sizes: [32, 1]
    num_columns: 10
    dropout: 0.5
    activation: relu
    last_dropout: 0
    last_activation: identity
  readout:
    _target_: torch.nn.Identity
  optimizer:
    _target_: torch.optim.Adam
    lr: 0.01
    weight_decay: 0.0005
  loss:
    _target_: torch.nn.L1Loss