# @package _group_
name: vae
_target_: model.Stim2StimEMG
params:
  latent_dim: 16
  beta: 0.001
  network:
    encoder:
      _target_: layers.feedforward.MLP
      in_size: 15
      hidden_sizes: [32, 32, 32]
      activation: elu
      last_activation: identity
    decoder:
      _target_: layers.feedforward.MLP
      in_size: 16
      hidden_sizes: [32, 32, 15]
      activation: elu
      last_activation: sigmoid
    core:
      _target_: layers.feedforward.MLP
      in_size: 16
      hidden_sizes: [256, 64]
      dropout: 0
      activation: elu
    readout:
      _target_: layers.feedforward.MLP
      in_size: 64
      hidden_sizes: 10
      activation: sigmoid
  optimizer:
    train:
      _target_: torch.optim.Adam
      lr: 0.003
      weight_decay: 0.0005
    inference:
      _target_: torch.optim.Adam
      lr: 0.001
  loss:
    stim:
      _target_: torch.nn.BCELoss
    emg:
      _target_: torch.nn.BCELoss